spring.application.name=payment-microservice

spring.datasource.url=jdbc:postgresql://localhost:5432/myfood-payment-db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

server.port=0
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka
# Enable multi instances of payment-microservice
eureka.instance.instance-id=${spring.application.name}:${random.int}

# how many request to make statistic to change state (open, close and half open)
resilience4j.circuitbreaker.instances.orderChangeStatus.slidingWindowSize: 3
# minimum request before circuit breaker enter in action
resilience4j.circuitbreaker.instances.orderChangeStatus.minimumNumberOfCalls: 2
# how many time to still in open state
resilience4j.circuitbreaker.instances.orderChangeStatus.waitDurationInOpenState: 50s