spring.application.name=payment

spring.datasource.url=jdbc:postgresql://localhost:5432/myfood-payment-db
spring.datasource.username=oltest
spring.datasource.password=master
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true